### ISSUE TITLE
Can't compile on Mac OS X

### ISSUE THREAD

**Issue by mmitech** [yacoin/yacoin#68]
I am having troubles compiling on Mac OS X, I think it has something to do with scrypt-x86.S and its nomacros, I've used pooler's nomacro.pl and commented this https://github.com/yacoin/yacoin/blob/master/src/scrypt-jane/code/scrypt-jane-portable-x86.h#L5-18 in order to make it compile, but it will crash every time it receives a block.

**Comment by ya4-old-c-coder** [comment]
You might try removing the "USE_ASM=1" statements from the build, if you are using yacoin-qt.pro or makefile.osx, depending on whether you are making the gui qt or the daemon.   I just looked at the makefile.osx, and I don't see any USE_ASM=1 statements, so I think it needs fixing!?

I use MSVC++ (Express) on Windows 8.1 so I don't know OS X, and MS can't digest the .S files anyway.  I find that there is not much difference in speed at N factor 17, between the USE_ASM=1 and the non USE_ASM=1 versions, using gcc on Windows, at least on my machine.  I build both gcc and MS daemons.  I find it so much easier to debug the daemon using MS real time full screen debugger in (the free) MSVS IDE.

Hope this helps... Ron

**Comment by mmitech** [comment]
There is no USE_ASM in the qt.pro !! yes I am trying to build Qt client for Mac OS X.

**Comment by ya4-old-c-coder** [comment]
You should then "fiddle" your YACoin-qt.pro file to contain no *.S files and instead add scrypt-generic.c to the sources list in the ...Qt.pro file.   Or you could do the same to the makefile.release or makefile.debug that the ...Qt.pro file produces!  Then try that.  What does the Qt debug file show, whatever and where ever it is!?

Ron

**Comment by mmitech** [comment]
it was showing me a memory leak for libcrypto, I used Macport instead of homebrew and it worked just fine (macport build everything from source).
